version: '2'
networks:
    default:

services:
    app:
        image: kaiyuanshe/osschat:develop
        volumes:
            - .env:/app/.env
        restart: always
        environment:
            - BROLOG_LEVEL=verbose